### ISSUE TITLE
Tokenizer Issue

### ISSUE THREAD

**Issue by 1shanpanta** [1shanpanta/Nepali-LLM#7]
Tokenizer is associated tokens with negative values. Look at data/nepali_tokenizer.vocab for further information. 

Example : 

"""

ा▁	-0
ो▁	-1
को▁	-2
्र	-3
न्	-4
"""

Tokenizers should give results like : 

ा▁	0
ो▁	1
को▁	2
्र	3
न्	4

Can't figure out what's wrong with the code. Help @SamirWagle.

For further information about Tokenizers , please watch Karpathy's videos.

**Comment by SamirWagle** [comment]
Check it out, In the transformer file. It seems correct.
